### ISSUE TITLE
TypeError: Missing required parameter 'digestmod'.

### ISSUE THREAD

**Issue by afrizal423** [cwkfr/cinema21-py#1]
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\afriz\AppData\Local\Programs\Python\Python38\lib\site-packages\cinema21.py", line 75, in cities
    result = self._post(data).json()
  File "C:\Users\afriz\AppData\Local\Programs\Python\Python38\lib\site-packages\cinema21.py", line 66, in _post
    "auth_key": self._getAuthKey(),  # Cache if hurt
  File "C:\Users\afriz\AppData\Local\Programs\Python\Python38\lib\site-packages\cinema21.py", line 28, in _getAuthKey
    a_hmac = hmac.new(a_hex.encode(), b_hex.encode()).hexdigest()
  File "C:\Users\afriz\AppData\Local\Programs\Python\Python38\lib\hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "C:\Users\afriz\AppData\Local\Programs\Python\Python38\lib\hmac.py", line 51, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.

Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by Shivelight** [comment]
Thanks for reporting, this issue is fixed with 2e22a9b275d9911e37790bd29b46b27f37647d7e.

You can copy the changes or install from pip:

```
pip install git+https://github.com/Shivelight/cinema21-py.git@2e22a9b275d9911e37790bd29b46b27f37647d7e
```

Anyway, I don't have time to maintain this project for now. There might be another issue, such as outdated API. I'll rewrite this when I have time, or perhaps using a better API.
